baseURL = 'https://www.lprakashv.com/'
languageCode = 'en-us'
title = 'LPRAKASHV TECH BLOG'
copyright = "© Lalit Prakash Vatsal"

theme = "archie"

# Code Highlight
# pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 10 # articles per page

# Social Tags

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/lprakashv/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lprakashv"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/lprakashv/"

[[params.social]]
name = "stackoverflow"
icon = "stackoverflow"
url = "https://stackoverflow.com/users/4066802/lprakashv?tab=profile"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
# url = "/about"
url = "https://github.com/lprakashv/lprakashv"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[params.adsense]
client = "ca-pub-3468549466738898"
inArticleSlot = "5223452966"
horizontalSlot = "5126431802"
verticalSlot = "6861065745"

[params.analytics]
gtagId = "G-DNE09NG226"
